# Generated by Django 3.2.16 on 2023-05-24 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('pub_date', 'id'), 'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
    ]
